name: Validate

on: pull_request

jobs:
  release:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci

      - name: Cache Dependencies
        id: deps
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
            ./packages/angular/node_modules
            ./packages/core/node_modules
            ./packages/react/node_modules
            ./packages/svelte/node_modules
            ./packages/vue/node_modules
            ./packages/vue-next/node_modules
          key: ${{ runner.os }}-${{ hashFiles('packages/*/package-lock.json') }}

      - name: Install Root Dependencies
        if: steps.rootDeps.outputs.cache-hit != 'true'
        run: npm run bootstrap

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint
